### ISSUE TITLE
How to extend the container with custom inference code?

### ISSUE THREAD

**Issue by artmatsak** [aws/sagemaker-pytorch-inference-toolkit#61]
I'm looking to extend the `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-eia:1.3.1-cpu-py36-ubuntu16.04` container for inference with Fairseq and BART. I've built my container and pushed it to ECR but I'm getting this error when running inference:

```
Please provide a model_fn implementation.
See documentation for model_fn at https://github.com/aws/sagemaker-python-sdk 
```

My Dockerfile is as follows:

```
ARG REGION=us-east-1

FROM 763104351884.dkr.ecr.$REGION.amazonaws.com/pytorch-inference-eia:1.3.1-cpu-py36-ubuntu16.04

ENV PATH="/opt/ml/code:${PATH}"

COPY /bart /opt/ml/code

RUN pip3 install -r /opt/ml/code/requirements.txt

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code

ENV SAGEMAKER_PROGRAM bart.py
```

`bart.py` contains the implementation of `model_fn` but apparently it isn't getting picked up. I've based my Dockerfile off of this one:

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/pytorch_extending_our_containers/container/Dockerfile

I assume things have changed and I have to provide my inference code in a different way. How do I do that please?

**Comment by artmatsak** [comment]
Anyone please?

**Comment by nadiaya** [comment]
Yes, the example you are using was for a different container.

Since we switched to use MMS as our model server inside the container the code now needs to be copied under /opt/ml/model/code/ .

**Comment by shamazharikh** [comment]
Hi,
I was facing the same issue, below is the Dockerfile I am using. It seems the model_fn is still not being read. @artmatsak Were you able to solve this issue?
@nadiaya Any help here would be appreciated!
```
ARG REGION=us-east-1

FROM 763104351884.dkr.ecr.$REGION.amazonaws.com/pytorch-inference-eia:1.3.1-cpu-py36-ubuntu16.04

ENV PATH="/opt/ml/code:${PATH}"

COPY /src /opt/ml/model/code

RUN pip3 install -r /opt/ml/code/requirements.txt

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/model/code

ENV SAGEMAKER_PROGRAM serve.py
```

**Comment by velenciucsergiu** [comment]
hello. Just out of the curiosity : in current release, do we have the possibility to have multi/model capabilities for pytorch containers?

**Comment by ajaykarpur** [comment]
> hello. Just out of the curiosity : in current release, do we have the possibility to have multi/model capabilities for pytorch containers?

@velenciucsergiu Multi-model support is available for PyTorch 1.4.0 and 1.5.0:

https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/c4e7abc49aeebc2f9b6035337548a90e4330113d/docker/1.4.0/py2/Dockerfile.cpu#L5

https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/c4e7abc49aeebc2f9b6035337548a90e4330113d/docker/1.4.0/py3/Dockerfile.cpu#L5

https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/c4e7abc49aeebc2f9b6035337548a90e4330113d/docker/1.5.0/py3/Dockerfile.cpu#L5

**Comment by josephjohansson** [comment]
I seem to have figured out the issue here. It seems that when the image is being spun up as an endpoint, there is some code that removes all files inside /opt/ml/model BEFORE copying  and unzipping model.tar.gz from S3. If you package your custom inference code in model.tar.gz then it will work. I have spent many hours figuring this out. Also, your saved model should be called model_0.pth as that is what MMS will pass to your custom inference code as the parameter model_dir. 

model.tar.gz
|- model_0.pth
|- code
|   |- inference.py

This sort of behavior from the code is in fact really concerning because it means that in order to change your custom inference code, you need to repackage your model data. This really makes working with this container setup in a CICD way clunky and hacky at best. 

At the very least, we should be adding what I mentioned above to the README or documentation for this project since its incredibly unclear how you would add your own custom inference code.

**Comment by RahulDamineni** [comment]
Expanding on @josephjohansson's answer, to extend pre-built images with custom inference code for TensorFlow serving, you need to package your inference code so that the `model.tar.gz` extracts like this: 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/13296814/157163023-e912215c-24f4-4d65-8549-b36f08e20ce0.png">


To pack it that way, you should run 
`tar -czf model.tar.gz <model_dir> <code_dir>`

I found this out by using [SageMaker's TensorFlowModel](https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/sagemaker.tensorflow.html#sagemaker.tensorflow.model.TensorFlowModel) API to package a model with an `entry_point` and inspecting its contents. 

They should really expand details [here](https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/deploying_tensorflow_serving.html#what-happens-when-deploy-is-called) so an unsuspecting dev would know what's happening in the background.

**Comment by holopekochan** [comment]
The AWS documentation was confused since it only has 1 document for training [Extend a Prebuilt Container](https://docs.aws.amazon.com/sagemaker/latest/dg/prebuilt-containers-extend.html)
Since it did not mention that different sagemaker container required different proceed, it confused me.
So I followed the doc and add this to Docker with my inference code
```
ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
COPY inference.py /opt/ml/code/inference.py
ENV SAGEMAKER_PROGRAM inference.py
```
I spend a long time until I read the code and comments here.
Now, I understand that the code above is not for sagemaker-pytorch-inference-container, but for sagemaker-inference-container. And, sagemaker-pytorch-inference-container should used MMS, so it need to put the inference.py in /code inside the tar.gz

**Comment by sephiartlist** [comment]
@josephjohansson 
Does [this](https://github.com/aws/sagemaker-pytorch-inference-toolkit/issues/61#issuecomment-665980501) also relate to [Docker containers](https://docs.aws.amazon.com/sagemaker/latest/dg/prebuilt-containers-extend.html)? and if so how?

**Comment by davidthomas426** [comment]
Documentation on using this package with custom inference code, including model artifact structure, as well as how SageMaker runs the container, can be found here:
* https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#model-directory-structure
* https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html

I'll  summarize certain relevant details that should clear up confusion in this thread.

When deploying your model to a SageMaker Endpoint, you first create a SageMaker Model from your model artifact, either using SageMaker's CreateModel API (https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModel.html) or with the SageMaker Python SDK (https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#create-a-pytorchmodel-object). You then create a SageMaker endpoint. When SageMaker deploys the model, SageMaker downloads and unpacks the model artifact and mounts the unpacked directory at /opt/ml/model in the container as a readonly Docker volume.
